-- PostgreSQL schema for AVEC Microcredit. Applied automatically when DATABASE_URL is set.
-- IDs remain importable from SQLite; use the data migration script before serving production traffic.

CREATE TABLE IF NOT EXISTS groups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            country TEXT,
            province TEXT,
            city TEXT,
            currency TEXT,
            phone TEXT,
            wallet REAL DEFAULT 0,
            blocked SMALLINT DEFAULT 0,
            cycle_length INTEGER DEFAULT 6,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS members (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT,
            member_id TEXT UNIQUE,
            prenom TEXT,
            name TEXT NOT NULL,
            phone TEXT,
            id_number TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            pin TEXT,
            parrain TEXT,
            role TEXT,
            role_origin TEXT NOT NULL DEFAULT 'member',
            password TEXT,
            wallet REAL DEFAULT 0,
            contribution REAL DEFAULT 0,
            cycle_contribution REAL DEFAULT 0,
            credit REAL DEFAULT 0,
            interest REAL DEFAULT 0,
            repayment REAL DEFAULT 0,
            withdrawals_date TEXT,
            withdrawals_count INTEGER DEFAULT 0,
            refresh_token TEXT,
            credit_request TEXT,
            availability TEXT NOT NULL DEFAULT 'offline',
            profile_photo_filename TEXT,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            action TEXT NOT NULL,
            date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS chat_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            sender TEXT NOT NULL,
            sender_member_id BIGINT,
            message TEXT NOT NULL,
            recipient TEXT,
            conversation_type TEXT NOT NULL DEFAULT 'group',
            date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS message_reactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            emoji TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(message_id, member_id, emoji),
            FOREIGN KEY (message_id) REFERENCES chat_messages (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS chat_attachments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            uploader_member_id BIGINT NOT NULL,
            message_id BIGINT,
            original_name TEXT NOT NULL,
            stored_name TEXT NOT NULL UNIQUE,
            mime_type TEXT NOT NULL,
            size_bytes INTEGER NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (uploader_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (message_id) REFERENCES chat_messages (id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS meetings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            creator_member_id BIGINT NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            starts_at TEXT NOT NULL,
            ends_at TEXT NOT NULL,
            meeting_type TEXT NOT NULL DEFAULT 'conference',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (creator_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS meeting_invites (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            meeting_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            response TEXT NOT NULL DEFAULT 'pending',
            responded_at TIMESTAMPTZ,
            UNIQUE(meeting_id, member_id),
            FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS platform_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identifier TEXT NOT NULL UNIQUE,
            prenom TEXT NOT NULL,
            name TEXT NOT NULL,
            phone TEXT UNIQUE,
            password TEXT NOT NULL,
            identity_number TEXT,
            phone_verified_at TIMESTAMPTZ,
            pin_configured INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
            visibility TEXT NOT NULL DEFAULT 'friends' CHECK (visibility IN ('public', 'friends', 'private')),
            availability TEXT NOT NULL DEFAULT 'offline' CHECK (availability IN ('online', 'offline', 'busy')),
            internal_wallet REAL NOT NULL DEFAULT 0,
            momo_wallet REAL NOT NULL DEFAULT 0,
            avatar_media_id BIGINT,
            refresh_token TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS wallet_topups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payment_id TEXT NOT NULL UNIQUE,
            idempotency_key TEXT NOT NULL UNIQUE,
            account_id BIGINT NOT NULL,
            provider TEXT NOT NULL CHECK (provider IN ('momo_sandbox', 'card_sandbox')),
            amount_minor INTEGER NOT NULL CHECK (amount_minor >= 100 AND amount_minor <= 100000000),
            currency TEXT NOT NULL DEFAULT 'USD',
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed')),
            confirmed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS platform_account_memberships (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id BIGINT NOT NULL,
            group_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL UNIQUE,
            status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(account_id, group_id),
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (group_id) REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_join_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            note TEXT,
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
            reviewed_by_account_id BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TIMESTAMPTZ,
            UNIQUE(group_id, account_id),
            FOREIGN KEY (group_id) REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_invitations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            invited_by_account_id BIGINT NOT NULL,
            role TEXT NOT NULL DEFAULT 'membre',
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            responded_at TIMESTAMPTZ,
            UNIQUE(group_id, account_id),
            FOREIGN KEY (group_id) REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_elections (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            role TEXT NOT NULL CHECK (role IN ('president', 'vice_president', 'secretaire', 'comptable')),
            title TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed_elected', 'closed_unfilled')),
            proposed_by_member_id BIGINT NOT NULL,
            closed_by_member_id BIGINT,
            elected_member_id BIGINT,
            active_member_count_at_close INTEGER,
            required_votes INTEGER,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            closed_at TIMESTAMPTZ,
            FOREIGN KEY (group_id) REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (proposed_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (closed_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (elected_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_election_candidates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            election_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            UNIQUE(election_id, member_id),
            FOREIGN KEY (election_id) REFERENCES group_elections(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_election_votes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            election_id BIGINT NOT NULL,
            voter_member_id BIGINT NOT NULL,
            candidate_member_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(election_id, voter_member_id),
            FOREIGN KEY (election_id) REFERENCES group_elections(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (voter_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (candidate_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS group_election_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            election_id BIGINT NOT NULL,
            group_id BIGINT NOT NULL,
            actor_member_id BIGINT,
            action TEXT NOT NULL,
            details_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (election_id) REFERENCES group_elections(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (group_id) REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (actor_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS account_notifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id BIGINT NOT NULL,
            kind TEXT NOT NULL,
            message TEXT NOT NULL,
            reference_type TEXT,
            reference_id BIGINT,
            read_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS friendships (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_one_id BIGINT NOT NULL,
            account_two_id BIGINT NOT NULL,
            requested_by_account_id BIGINT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            responded_at TIMESTAMPTZ,
            UNIQUE(account_one_id, account_two_id),
            FOREIGN KEY (account_one_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_two_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS direct_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sender_account_id BIGINT NOT NULL,
            recipient_account_id BIGINT NOT NULL,
            message TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (sender_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (recipient_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS direct_message_attachments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sender_account_id BIGINT NOT NULL,
            recipient_account_id BIGINT NOT NULL,
            message_id BIGINT,
            original_name TEXT NOT NULL,
            stored_name TEXT NOT NULL UNIQUE,
            mime_type TEXT NOT NULL,
            size_bytes INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (sender_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (recipient_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (message_id) REFERENCES direct_messages(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS direct_message_reactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            emoji TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(message_id, account_id, emoji),
            FOREIGN KEY (message_id) REFERENCES direct_messages(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS media_files (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_account_id BIGINT NOT NULL,
            stored_name TEXT NOT NULL UNIQUE,
            original_name TEXT NOT NULL,
            mime_type TEXT NOT NULL,
            size_bytes INTEGER NOT NULL,
            purpose TEXT NOT NULL CHECK (purpose IN ('avatar', 'post')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (owner_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_posts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            author_account_id BIGINT NOT NULL,
            body TEXT NOT NULL,
            visibility TEXT NOT NULL DEFAULT 'friends' CHECK (visibility IN ('public', 'friends')),
            media_id BIGINT,
            moderation_status TEXT NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('approved', 'pending', 'removed')),
            moderation_reason TEXT,
            review_tag TEXT,
            deleted_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (media_id) REFERENCES media_files(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS post_reactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            reaction TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(post_id, account_id, reaction),
            FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS post_comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id BIGINT NOT NULL,
            author_account_id BIGINT NOT NULL,
            body TEXT NOT NULL,
            parent_comment_id BIGINT,
            moderation_status TEXT NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('approved', 'pending', 'removed')),
            moderation_reason TEXT,
            review_tag TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (parent_comment_id) REFERENCES post_comments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS comment_reactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            comment_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            reaction TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(comment_id, account_id, reaction),
            FOREIGN KEY (comment_id) REFERENCES post_comments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_sandbox_ledger (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payment_id TEXT NOT NULL UNIQUE,
            idempotency_key TEXT NOT NULL UNIQUE,
            content_type TEXT NOT NULL CHECK (content_type IN ('post', 'comment')),
            content_id BIGINT NOT NULL,
            charged_account_id BIGINT NOT NULL,
            post_author_account_id BIGINT,
            amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
            platform_amount_minor INTEGER NOT NULL CHECK (platform_amount_minor >= 0),
            author_amount_minor INTEGER NOT NULL CHECK (author_amount_minor >= 0),
            currency TEXT NOT NULL DEFAULT 'USD',
            sandbox SMALLINT NOT NULL DEFAULT 1 CHECK (sandbox = 1),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (charged_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (post_author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_moderation_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_id TEXT NOT NULL UNIQUE,
            content_type TEXT NOT NULL CHECK (content_type IN ('post', 'comment', 'account')),
            content_id BIGINT NOT NULL,
            action TEXT NOT NULL CHECK (action IN ('queued', 'approved', 'removed', 'banned')),
            actor_member_id BIGINT,
            reason TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS post_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id BIGINT NOT NULL,
            reporter_account_id BIGINT NOT NULL,
            reason TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(post_id, reporter_account_id),
            FOREIGN KEY (post_id) REFERENCES social_posts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (reporter_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            creator_account_id BIGINT NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            starts_at TEXT NOT NULL,
            ends_at TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (creator_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_event_invites (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            response TEXT NOT NULL DEFAULT 'pending' CHECK (response IN ('pending', 'accepted', 'declined')),
            UNIQUE(event_id, account_id),
            FOREIGN KEY (event_id) REFERENCES social_events(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_content_media (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stored_name TEXT NOT NULL UNIQUE,
            original_name TEXT NOT NULL,
            mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/gif', 'image/webp')),
            size_bytes INTEGER NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 3145728),
            uploaded_by_member_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (uploaded_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_content (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            content_type TEXT NOT NULL CHECK (content_type IN ('announcement', 'advertisement')),
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            audience TEXT NOT NULL DEFAULT 'public' CHECK (audience IN ('public', 'members')),
            placement TEXT NOT NULL DEFAULT 'news' CHECK (placement IN ('news', 'home')),
            media_id BIGINT,
            starts_at TIMESTAMPTZ NOT NULL,
            ends_at TIMESTAMPTZ,
            active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
            archived_at TIMESTAMPTZ,
            created_by_member_id BIGINT NOT NULL,
            updated_by_member_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (media_id) REFERENCES public_content_media(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (created_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (updated_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_content_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_id TEXT NOT NULL UNIQUE,
            content_id BIGINT,
            actor_member_id BIGINT NOT NULL,
            action TEXT NOT NULL CHECK (action IN ('created', 'updated', 'archived')),
            details_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (content_id) REFERENCES public_content(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (actor_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS paid_public_contents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            author_account_id BIGINT NOT NULL,
            content_type TEXT NOT NULL CHECK (content_type IN ('post', 'announcement', 'advertisement')),
            body TEXT NOT NULL,
            title TEXT,
            product_price TEXT,
            product_total TEXT,
            availability TEXT,
            address TEXT,
            contact_phone TEXT,
            contact_email TEXT,
            media_ids_json TEXT NOT NULL DEFAULT '[]',
            duration_days INTEGER NOT NULL DEFAULT 1,
            publication_status TEXT NOT NULL CHECK (publication_status IN ('payment_pending', 'pending_review', 'approved', 'removed')),
            moderation_reason TEXT,
            payment_status TEXT NOT NULL CHECK (payment_status IN ('pending', 'succeeded', 'failed')),
            payment_method TEXT NOT NULL CHECK (payment_method IN ('internal_wallet', 'momo_sandbox')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            published_at TIMESTAMPTZ,
            FOREIGN KEY (author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS paid_public_content_payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payment_id TEXT NOT NULL UNIQUE,
            idempotency_key TEXT NOT NULL UNIQUE,
            content_id BIGINT NOT NULL UNIQUE,
            account_id BIGINT NOT NULL,
            provider TEXT NOT NULL CHECK (provider IN ('internal_wallet', 'momo_sandbox')),
            amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
            currency TEXT NOT NULL DEFAULT 'USD',
            status TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed')),
            external_reference TEXT,
            confirmed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (content_id) REFERENCES paid_public_contents(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS paid_public_content_ledger (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entry_id TEXT NOT NULL UNIQUE,
            payment_id TEXT NOT NULL UNIQUE,
            content_id BIGINT NOT NULL,
            account_id BIGINT NOT NULL,
            platform_amount_minor INTEGER NOT NULL CHECK (platform_amount_minor >= 0),
            currency TEXT NOT NULL DEFAULT 'USD',
            sandbox INTEGER NOT NULL DEFAULT 1 CHECK (sandbox = 1),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (payment_id) REFERENCES paid_public_content_payments(payment_id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (content_id) REFERENCES paid_public_contents(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS paid_public_content_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_id TEXT NOT NULL UNIQUE,
            content_id BIGINT NOT NULL,
            payment_id TEXT,
            actor_account_id BIGINT NOT NULL,
            action TEXT NOT NULL CHECK (action IN ('created', 'wallet_deducted', 'momo_intent_created', 'momo_confirmed', 'published', 'pending_review', 'removed')),
            details_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (content_id) REFERENCES paid_public_contents(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (actor_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS paid_public_content_moderation_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_id TEXT NOT NULL UNIQUE,
            content_id BIGINT NOT NULL,
            action TEXT NOT NULL CHECK (action IN ('approved', 'removed', 'banned')),
            actor_member_id BIGINT,
            reason TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (content_id) REFERENCES paid_public_contents(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (actor_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_item_comments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source TEXT NOT NULL CHECK (source IN ('member_content')),
            content_id BIGINT NOT NULL,
            author_account_id BIGINT NOT NULL,
            body TEXT NOT NULL,
            moderation_status TEXT NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('approved', 'pending', 'removed')),
            moderation_reason TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (content_id) REFERENCES paid_public_contents(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_comment_receipts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payment_id TEXT NOT NULL UNIQUE,
            idempotency_key TEXT NOT NULL UNIQUE,
            comment_id BIGINT NOT NULL UNIQUE,
            charged_account_id BIGINT NOT NULL,
            content_author_account_id BIGINT NOT NULL,
            amount_minor INTEGER NOT NULL CHECK (amount_minor = 25),
            platform_amount_minor REAL NOT NULL CHECK (platform_amount_minor = 12.5),
            author_amount_minor REAL NOT NULL CHECK (author_amount_minor = 12.5),
            currency TEXT NOT NULL DEFAULT 'USD',
            sandbox INTEGER NOT NULL DEFAULT 1 CHECK (sandbox = 1),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (comment_id) REFERENCES public_item_comments(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (charged_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (content_author_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS public_flashes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category TEXT NOT NULL CHECK (category IN ('sport', 'international', 'local')),
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            locality_tag TEXT,
            audience_tag TEXT,
            active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
            starts_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            ends_at TIMESTAMPTZ,
            created_by_member_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (created_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS social_channel_links (
            network TEXT PRIMARY KEY CHECK (network IN ('facebook', 'instagram', 'youtube', 'tiktok')),
            url TEXT NOT NULL,
            active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
            updated_by_member_id BIGINT NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (updated_by_member_id) REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS platform_momo (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            country TEXT NOT NULL,
            provider TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            currency TEXT,
            description TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(country, provider)
        );

CREATE TABLE IF NOT EXISTS fraud_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            reporter_member_id BIGINT NOT NULL,
            details TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (reporter_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS review_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id BIGINT NOT NULL,
            requester_member_id BIGINT NOT NULL,
            message TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            resolved_at TIMESTAMPTZ,
            resolved_by_member_id BIGINT,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (requester_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (resolved_by_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS financial_ledger (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transaction_id TEXT NOT NULL UNIQUE,
            group_id BIGINT NOT NULL,
            member_id BIGINT,
            transaction_type TEXT NOT NULL,
            amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
            currency TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed', 'reversed')),
            provider TEXT NOT NULL,
            idempotency_key TEXT NOT NULL UNIQUE,
            external_reference TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS payment_attempts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attempt_id TEXT NOT NULL UNIQUE,
            transaction_id TEXT NOT NULL,
            group_id BIGINT NOT NULL,
            member_id BIGINT,
            provider TEXT NOT NULL,
            direction TEXT NOT NULL CHECK (direction IN ('collection', 'disbursement')),
            status TEXT NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed', 'reversed')),
            request_json TEXT NOT NULL,
            result_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (transaction_id) REFERENCES financial_ledger (transaction_id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS payment_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_record_id TEXT NOT NULL UNIQUE,
            transaction_id TEXT,
            group_id BIGINT,
            provider TEXT,
            event_type TEXT NOT NULL,
            status TEXT,
            provider_event_id TEXT,
            payload_json TEXT NOT NULL DEFAULT '{}',
            actor_member_id BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(provider, provider_event_id)
        );

CREATE TABLE IF NOT EXISTS payment_operations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            operation_id TEXT NOT NULL UNIQUE,
            group_id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            operation_type TEXT NOT NULL CHECK (operation_type = 'loan_disbursement'),
            amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
            currency TEXT NOT NULL,
            provider TEXT NOT NULL,
            destination_phone TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('pending_approval', 'approved', 'rejected', 'disbursed')),
            requested_by_member_id BIGINT NOT NULL,
            approved_by_member_id BIGINT,
            transaction_id TEXT,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (group_id) REFERENCES groups (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE,
            FOREIGN KEY (transaction_id) REFERENCES financial_ledger (transaction_id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS payment_idempotency (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            idempotency_key TEXT NOT NULL UNIQUE,
            operation_scope TEXT NOT NULL,
            response_status INTEGER NOT NULL,
            response_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS financial_audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_id TEXT NOT NULL UNIQUE,
            transaction_id TEXT,
            operation_id TEXT,
            group_id BIGINT,
            actor_member_id BIGINT,
            action TEXT NOT NULL,
            details_json TEXT NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE IF NOT EXISTS deployment_settings (
            id BIGINT PRIMARY KEY CHECK (id = 1),
            public_base_url TEXT NOT NULL DEFAULT '',
            allowed_origins_json TEXT NOT NULL DEFAULT '[]',
            hosting_provider TEXT NOT NULL DEFAULT 'self_hosted',
            sms_provider TEXT NOT NULL DEFAULT 'sandbox',
            video_provider TEXT NOT NULL DEFAULT 'none',
            turn_urls_json TEXT NOT NULL DEFAULT '[]',
            momo_providers_json TEXT NOT NULL DEFAULT '[]',
            maintenance_mode INTEGER NOT NULL DEFAULT 0 CHECK (maintenance_mode IN (0, 1)),
            production_ready INTEGER NOT NULL DEFAULT 0 CHECK (production_ready IN (0, 1)),
            backup_verified INTEGER NOT NULL DEFAULT 0 CHECK (backup_verified IN (0, 1)),
            sandbox_acknowledged INTEGER NOT NULL DEFAULT 0 CHECK (sandbox_acknowledged IN (0, 1)),
            updated_by_member_id BIGINT,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (updated_by_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

CREATE TABLE IF NOT EXISTS deployment_settings_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            actor_member_id BIGINT NOT NULL,
            action TEXT NOT NULL CHECK (action = 'updated'),
            settings_json TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (actor_member_id) REFERENCES members (id) DEFERRABLE INITIALLY IMMEDIATE
        );

-- Columns introduced by prior SQLite startup migrations are part of the PostgreSQL baseline.
ALTER TABLE groups ADD COLUMN IF NOT EXISTS momo_provider TEXT;
ALTER TABLE direct_messages ADD COLUMN IF NOT EXISTS attachment_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_group_elections_group_status ON group_elections(group_id, status);
CREATE INDEX IF NOT EXISTS idx_group_election_votes_election ON group_election_votes(election_id);
CREATE INDEX IF NOT EXISTS idx_memberships_account_group ON platform_account_memberships(account_id, group_id);
CREATE INDEX IF NOT EXISTS idx_join_requests_group_status ON group_join_requests(group_id, status);
CREATE INDEX IF NOT EXISTS idx_notifications_account_created ON account_notifications(account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_friendships_status ON friendships(account_one_id, account_two_id, status);
CREATE INDEX IF NOT EXISTS idx_direct_messages_conversation ON direct_messages(sender_account_id, recipient_account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_posts_created ON social_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_post_comments_post ON post_comments(post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_social_sandbox_ledger_content ON social_sandbox_ledger(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_social_moderation_pending ON social_posts(moderation_status, created_at);
CREATE INDEX IF NOT EXISTS idx_public_content_feed ON public_content(audience, active, archived_at, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_paid_public_content_feed ON paid_public_contents(publication_status, payment_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_financial_ledger_group_created ON financial_ledger (group_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_events_transaction ON payment_events (transaction_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_operations_group ON payment_operations (group_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_platform_conversation ON chat_messages (group_id, conversation_type, date);
CREATE INDEX IF NOT EXISTS idx_chat_attachments_group ON chat_attachments (group_id, message_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_accounts_identity_number ON platform_accounts(identity_number) WHERE identity_number IS NOT NULL;


CREATE OR REPLACE FUNCTION prevent_immutable_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER public_content_audit_immutable_update
BEFORE UPDATE ON public_content_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER public_content_audit_immutable_delete
BEFORE DELETE ON public_content_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER paid_public_content_ledger_immutable_update
BEFORE UPDATE ON paid_public_content_ledger
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER paid_public_content_ledger_immutable_delete
BEFORE DELETE ON paid_public_content_ledger
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER paid_public_content_audit_immutable_update
BEFORE UPDATE ON paid_public_content_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER paid_public_content_audit_immutable_delete
BEFORE DELETE ON paid_public_content_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER public_comment_receipts_immutable_update
BEFORE UPDATE ON public_comment_receipts
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER public_comment_receipts_immutable_delete
BEFORE DELETE ON public_comment_receipts
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER deployment_settings_audit_immutable_update
BEFORE UPDATE ON deployment_settings_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER deployment_settings_audit_immutable_delete
BEFORE DELETE ON deployment_settings_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER financial_ledger_immutable_update
BEFORE UPDATE ON financial_ledger
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER financial_ledger_immutable_delete
BEFORE DELETE ON financial_ledger
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER payment_attempts_immutable_update
BEFORE UPDATE ON payment_attempts
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER payment_attempts_immutable_delete
BEFORE DELETE ON payment_attempts
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER payment_events_immutable_update
BEFORE UPDATE ON payment_events
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER payment_events_immutable_delete
BEFORE DELETE ON payment_events
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER financial_audit_log_immutable_update
BEFORE UPDATE ON financial_audit_log
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER financial_audit_log_immutable_delete
BEFORE DELETE ON financial_audit_log
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

