-- Internal wallet journal and transfers. Amounts are always stored in minor units.
ALTER TABLE platform_accounts ADD COLUMN IF NOT EXISTS wallet_currency TEXT NOT NULL DEFAULT 'USD';

CREATE TABLE IF NOT EXISTS wallet_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT NOT NULL UNIQUE,
    sender_account_id BIGINT NOT NULL,
    recipient_account_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    currency TEXT NOT NULL,
    memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (sender_account_id <> recipient_account_id),
    FOREIGN KEY (sender_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
    FOREIGN KEY (recipient_account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS wallet_journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id TEXT NOT NULL UNIQUE,
    transfer_id TEXT NOT NULL,
    account_id BIGINT NOT NULL,
    entry_type TEXT NOT NULL CHECK (entry_type IN ('debit', 'credit')),
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    currency TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (transfer_id) REFERENCES wallet_transfers(transfer_id) DEFERRABLE INITIALLY IMMEDIATE,
    FOREIGN KEY (account_id) REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX IF NOT EXISTS idx_wallet_transfers_sender_created ON wallet_transfers(sender_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_transfers_recipient_created ON wallet_transfers(recipient_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_journal_account_created ON wallet_journal_entries(account_id, created_at DESC);

CREATE TRIGGER wallet_transfers_immutable_update
BEFORE UPDATE ON wallet_transfers
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER wallet_transfers_immutable_delete
BEFORE DELETE ON wallet_transfers
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER wallet_journal_entries_immutable_update
BEFORE UPDATE ON wallet_journal_entries
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER wallet_journal_entries_immutable_delete
BEFORE DELETE ON wallet_journal_entries
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();
