-- AVEC/Epargne product split and auditable cycle lifecycle.
ALTER TABLE groups ADD COLUMN IF NOT EXISTS group_type TEXT NOT NULL DEFAULT 'AVEC';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS savings_periodicity TEXT;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS savings_period INTEGER NOT NULL DEFAULT 1;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cycle_status TEXT NOT NULL DEFAULT 'open';
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cycle_number INTEGER NOT NULL DEFAULT 1;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cycle_started_at TIMESTAMPTZ;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cycle_closed_at TIMESTAMPTZ;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS cycle_closed_by_member_id BIGINT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS sponsor_account_id BIGINT;
ALTER TABLE group_invitations ADD COLUMN IF NOT EXISTS sponsor_account_id BIGINT;

ALTER TABLE groups DROP CONSTRAINT IF EXISTS groups_group_type_check;
ALTER TABLE groups ADD CONSTRAINT groups_group_type_check CHECK (group_type IN ('AVEC', 'Epargne'));
ALTER TABLE groups DROP CONSTRAINT IF EXISTS groups_savings_periodicity_check;
ALTER TABLE groups ADD CONSTRAINT groups_savings_periodicity_check CHECK (savings_periodicity IS NULL OR savings_periodicity IN ('weekly', 'monthly'));
ALTER TABLE groups DROP CONSTRAINT IF EXISTS groups_cycle_status_check;
ALTER TABLE groups ADD CONSTRAINT groups_cycle_status_check CHECK (cycle_status IN ('planning', 'open', 'closed'));
ALTER TABLE groups DROP CONSTRAINT IF EXISTS groups_savings_period_check;
ALTER TABLE groups ADD CONSTRAINT groups_savings_period_check CHECK (savings_period BETWEEN 1 AND 52);

CREATE TABLE IF NOT EXISTS group_cycle_beneficiaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
    cycle_number INTEGER NOT NULL,
    member_id BIGINT NOT NULL REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    beneficiary_order INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'paid')),
    locked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMPTZ,
    UNIQUE(group_id, cycle_number, member_id),
    UNIQUE(group_id, cycle_number, beneficiary_order)
);

CREATE TABLE IF NOT EXISTS group_cycle_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
    cycle_number INTEGER NOT NULL,
    actor_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    action TEXT NOT NULL CHECK (action IN ('created', 'beneficiary_order_locked', 'closed', 'restored', 'new_cycle')),
    details_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_groups_discovery_location ON groups(country, province, city);
CREATE INDEX IF NOT EXISTS idx_cycle_beneficiaries_group_cycle ON group_cycle_beneficiaries(group_id, cycle_number, beneficiary_order);
CREATE INDEX IF NOT EXISTS idx_cycle_audit_group_cycle ON group_cycle_audit(group_id, cycle_number, created_at DESC);
