CREATE TABLE IF NOT EXISTS meta_page_publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT NOT NULL UNIQUE,
    source TEXT NOT NULL CHECK (source IN ('public_content', 'social_post', 'paid_public_content', 'test')),
    source_content_id BIGINT,
    actor_member_id BIGINT NOT NULL REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    message_sha256 TEXT NOT NULL,
    page_post_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'published', 'failed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    CHECK ((source = 'test' AND source_content_id IS NULL) OR (source <> 'test' AND source_content_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS meta_page_publication_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id TEXT NOT NULL UNIQUE,
    publication_id TEXT NOT NULL REFERENCES meta_page_publications(publication_id) DEFERRABLE INITIALLY IMMEDIATE,
    actor_member_id BIGINT NOT NULL REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    action TEXT NOT NULL CHECK (action IN ('requested', 'published', 'failed')),
    details_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_meta_page_publications_source ON meta_page_publications(source, source_content_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meta_page_publications_active_source
ON meta_page_publications(source, source_content_id)
WHERE source <> 'test' AND status IN ('pending', 'published');

CREATE TRIGGER meta_page_publication_audit_immutable_update
BEFORE UPDATE ON meta_page_publication_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER meta_page_publication_audit_immutable_delete
BEFORE DELETE ON meta_page_publication_audit
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();
