ALTER TABLE platform_accounts ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE platform_accounts ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS intended_member_count INTEGER NOT NULL DEFAULT 20;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS starting_capital_minor INTEGER NOT NULL DEFAULT 10000;

CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_accounts_email_lower
ON platform_accounts (LOWER(email)) WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS group_creation_rules (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    min_member_count INTEGER NOT NULL DEFAULT 20 CHECK (min_member_count >= 1),
    max_member_count INTEGER NOT NULL DEFAULT 50 CHECK (max_member_count >= min_member_count),
    fee_per_member_minor INTEGER NOT NULL DEFAULT 100 CHECK (fee_per_member_minor >= 0),
    minimum_starting_capital_minor INTEGER NOT NULL DEFAULT 10000 CHECK (minimum_starting_capital_minor >= 0),
    updated_by_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO group_creation_rules (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS group_creation_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_id TEXT NOT NULL UNIQUE,
    group_id BIGINT NOT NULL UNIQUE REFERENCES groups(id) DEFERRABLE INITIALLY IMMEDIATE,
    account_id BIGINT NOT NULL REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
    intended_member_count INTEGER NOT NULL CHECK (intended_member_count >= 1),
    amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
    currency TEXT NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_creation_fees_account_created
ON group_creation_fees(account_id, created_at DESC);
