-- Sandbox-only personal-wallet withdrawal intents.  Funds are reserved before
-- an explicit simulated confirmation and every state transition is audited.
ALTER TABLE platform_accounts
    ADD COLUMN IF NOT EXISTS wallet_reserved_minor BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS wallet_withdrawal_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    withdrawal_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT NOT NULL UNIQUE,
    account_id BIGINT NOT NULL REFERENCES platform_accounts(id) DEFERRABLE INITIALLY IMMEDIATE,
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    currency TEXT NOT NULL,
    provider TEXT NOT NULL CHECK (provider = 'sandbox'),
    destination_phone TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('reserved', 'succeeded', 'failed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS wallet_withdrawal_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    withdrawal_id TEXT NOT NULL REFERENCES wallet_withdrawal_intents(withdrawal_id) DEFERRABLE INITIALLY IMMEDIATE,
    event_type TEXT NOT NULL CHECK (event_type IN ('reserved', 'succeeded', 'released')),
    amount_minor BIGINT NOT NULL CHECK (amount_minor > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_wallet_withdrawals_account_created
ON wallet_withdrawal_intents(account_id, created_at DESC);

CREATE TRIGGER wallet_withdrawal_events_immutable_update
BEFORE UPDATE ON wallet_withdrawal_events
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();

CREATE TRIGGER wallet_withdrawal_events_immutable_delete
BEFORE DELETE ON wallet_withdrawal_events
FOR EACH ROW EXECUTE FUNCTION prevent_immutable_change();
