-- Curated, human-approved assistant knowledge.  No private/group conversations,
-- account details, credentials, or financial records are eligible sources.
CREATE TABLE IF NOT EXISTS assistant_knowledge_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    locale TEXT NOT NULL CHECK (locale IN ('fr', 'en', 'rw', 'rn', 'sw', 'ln')),
    source_type TEXT NOT NULL CHECK (source_type IN ('curated_resource', 'public_post', 'public_comment', 'assistant_question')),
    source_reference TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'archived')),
    created_by_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    approved_by_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assistant_learning_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL CHECK (source_type IN ('public_post', 'public_comment', 'assistant_question')),
    source_reference TEXT NOT NULL UNIQUE,
    body TEXT NOT NULL,
    locale TEXT NOT NULL CHECK (locale IN ('fr', 'en', 'rw', 'rn', 'sw', 'ln')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    submitted_by_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    reviewed_by_member_id BIGINT REFERENCES members(id) DEFERRABLE INITIALLY IMMEDIATE,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_assistant_knowledge_approved
ON assistant_knowledge_entries(status, locale, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assistant_learning_pending
ON assistant_learning_submissions(status, created_at ASC);
